name: Auto Content Updater

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        run: npm run update-content

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature-branch
          base: master
          title: New content found in @nestjs/awesome-nestjs repository
          body: |
            @777Vasya77 This is an automated pull request created by GitHub Actions.
